require "digest"
require "sidekiq-middleware/version"
require "sidekiq-middleware/core_ext"
require "sidekiq-middleware/server/unique_jobs"
require "sidekiq-middleware/client/unique_jobs"
require "sidekiq-middleware/middleware"